version: '3.4'

services:
  administration_db:
    container_name: administration_db
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin1234"
      POSTGRES_DB: "administration_db"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_data:/root/.pgadmin
    
  awezomestore_administration_ms:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
