version: '3.4'

services:
  awezomestore_administration_ms:
    image: awezomestoreadministrationms:dev
    container_name: awezomestore_administration_ms
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "awezomestore_administration_ms"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\David Rojas\source\repos\awezomestore_administration_ms\awezomestore_administration_ms:/app
      - C:\Users\David Rojas\source\repos\awezomestore_administration_ms:/src
      - C:\Users\David Rojas\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\David Rojas\.nuget\packages\:/root/.nuget/packages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net5.0/awezomestore_administration_ms.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true